---
apiVersion: v1
kind: Namespace
metadata:
  name: ac-channel-acm
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gs-acm
  namespace: ac-channel-acm
spec:
  type: Git
  pathname: https://github.com/alojzcerne/acm.git
# pathname: https://github.com/open-cluster-management/application-samples.git
---
apiVersion: v1
kind: Namespace
metadata:
  #labels:
    #role: app
  name: ac-app-test
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: app-test
  namespace: ac-app-test
  labels:
    app: app-test-subscription
  annotations:
#   apps.open-cluster-management.io/github-path: ''
    apps.open-cluster-management.io/github-path: test
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/reconcile-option: merge
spec:
  channel: ac-channel-acm/gs-acm
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-clusters
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-clusters
  namespace: ac-app-test
spec:
  clusterSelector:
    matchExpressions: []
    matchLabels:
      environment: Dev
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: test
  namespace: ac-app-test
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - app-test-subscription
