kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lcl
  labels:
    local.storage.openshift.io/owner-name: lcl
    local.storage.openshift.io/owner-namespace: openshift-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ocs-operator-ac
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
