---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: installadmin
  namespace: openshift-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: installadmin
  namespace: openshift-storage
---
apiVersion: batch/v1
kind: Job
metadata:
  name: set-node-role
spec:
  template:
    spec:
      serviceAccountName: installadmin
      restartPolicy: Never
      containers:
      - name: infra
        image: registry.redhat.io/openshift4/ose-cli:v4.7
        command: ["/bin/sh",  "-c", "oc label node/worker01 node/worker02 node/worker03 cluster.ocs.openshift.io/openshift-storage=''"]
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: lcl
  labels:
    local.storage.openshift.io/owner-name: lcl
    local.storage.openshift.io/owner-namespace: openshift-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-storage
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ocs-operator-ac
  namespace: openshift-storage
spec:
  targetNamespaces:
    - openshift-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  namespace: openshift-storage
  labels:
    operators.coreos.com/ocs-operator.openshift-storage: ""
spec:
  channel: "stable-4.6"
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: 'true'
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
  finalizers:
    - storagecluster.ocs.openshift.io
spec:
  encryption: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - config: {}
      count: 1
      dataPVCTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: lcl
          volumeMode: Block
        status: {}
      name: ocs-deviceset-lcl
      placement: {}
      replica: 3
      resources: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocs4registry
  namespace: openshift-image-registry
spec: 
  storageClassName: ocs-storagecluster-cephfs
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests: 
      storage: 100Gi

